---
- name: Configure ISL ports (NXOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item }}
         no switchport
         no shut
         medium p2p
         ip unnumbered loopback0
         mtu 9216
  with_items: "{{ isl_ports[ansible_network_os] }}"
  tags: ospf-isl-cfg

- name: Configure OSPF paramaters (NXOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item }}
         ip ospf network point-to-point
         ip router ospf UNDERLAY area 0.0.0.0
  with_items: "{{ isl_ports[ansible_network_os] }}"
  tags: ospf-isl-cfg

      

