---
 - name: Add FRR repo key
   apt_key:
     url: https://deb-us.frrouting.org/frr/keys.asc
     state: present

 - name: Add FRR repo
   apt_repository:
     repo: deb https://deb-us.frrouting.org/frr focal frr-stable
     state: present
     update_cache: yes

 - name: Add FRR
   apt:
     name: frr
     state: present
 
