---
- name: Download running config
  connection: network_cli
  cli_command:
     command: show configuration
  register: backup

- name: Save to local file
  connection: network_cli
  copy:
     content: "{{backup.stdout}}"
     dest: "configs/{{ansible_network_os}}/{{inventory_hostname}}.cfg"
