---
- name: Configure eBGP Underlay ISL ports (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      {% for iface, value in ebgp_cfg[ansible_network_os][inventory_hostname].items() %}
      auto {{ iface }}
      iface {{ iface }}
         mtu 9216
         address {{ value.address }}
      {% endfor %}
    marker: '#{mark} isl-ports'
  notify:
    - ifup interfaces
