---
- name: Configure member hostbonds (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      {% for item in mh.mh_hostchannels[ansible_network_os] %}
      {% for port in item.ports %}
      auto {{ port }}
      iface {{ port }}
         mtu 9216    
         post-up ip link set promisc on dev {{ port }}
      {% endfor %}
      #
      auto {{ item.iface }}
      iface {{ item.iface }}
         bond-slaves {{ item.ports|join(' ') }}
         mtu 9216
         es-sys-mac {{ item.mh_mac }}
         bond-mode 802.3ad
         bond-min-links 1
         bond-lacp-rate 1
      #
      {% endfor %}
    marker: '#{mark} mh-member-ports'
