replication: ingress-replication
ibgp_asn: 64520
lo_addr: "{{ loopback_ip.split('/')[0] }}"
nxos_fabric_anycast_gw_mac: 00:00:00:11:12:10
underlay: ospf
overlay: ibgp
use_local_as: "{% if underlay == 'ebgp' and overlay == 'ibgp' %} true {% else %} false {% endif %}"


# l2_networks is keyed off of VLANID
l2_networks:
  10:
    vnid: 10
    vlanif: Vlan10
    ip_address: 172.16.1.254/24
    ip_unique: 172.16.1.1/24
    mcast_grp: 224.1.1.192
    ip_subnet: 172.16.1.0/24
    vrf: evpn-vrf

  20:
    vnid: 20
    vlanif: Vlan20
    ip_address: 172.16.2.254/24
    ip_unique: 172.16.2.1/24    
    mcast_grp: 224.1.1.192
    ip_subnet: 172.16.2.0/24
    vrf: evpn-vrf

  30:
    vnid: 30
    vlanif: Vlan30
    ip_address: 172.16.3.254/24
    ip_unique: 172.16.3.1/24        
    mcast_grp: 224.1.1.192
    ip_subnet: 172.16.3.0/24    
    vrf: evpn-vrf
    
  40:
    vnid: 40
    vlanif: Vlan40
    ip_address: 172.16.4.254/24
    ip_unique: 172.16.4.1/24        
    mcast_grp: 224.1.1.192
    ip_subnet: 172.16.4.0/24    
    vrf: evpn-vrf

evpn_l3_info:
  - vlan: 999
    vnid: 999
    vlanif: vlan999
    junos_vrf_loopback_ip:
      leaf01:
        10.0.0.101/32
      leaf02:
        10.0.0.102/32
      leaf03:
        10.0.0.103/32
      leaf04:
        10.0.0.104/32
      leaf05:
        10.0.0.105/32
      leaf06:
        10.0.0.106/32
      exit01:
        10.0.0.121/32
      exit02:
        10.0.0.122/32
    vrf: evpn-vrf


