---
- name: configure dcedge and firewall eBGP config
  become: yes
  blockinfile:
    path: /etc/frr/frr.conf
    block: |
      router bgp {{ bgp_asn }}
         neighbor FW peer-group
         neighbor FW remote-as external
         neighbor FW bfd
         {% for port in default_vrf_firewall_ports[ansible_network_os] %}
         neighbor {{ port.iface }} interface peer-group FW
         neighbor {{ port.iface }} local-as {{ default_vrf_asn }} no-prepend replace-as
         {% endfor %}
         !
         address-family ipv4 unicast
            neighbor FW activate
         exit-address-family
         !
      {% for vrf in evpn_vrfs %}
      route-map LOWER_AGGRT_PREF permit 10
         set local-preference 10
      !
      router bgp {{ ibgp_asn }} vrf {{ vrf }}
         bgp router-id {{ lo_addr }}
         no bgp default ipv4-unicast
         neighbor ISL peer-group
         neighbor ISL remote-as external
         {% for port in evpn_vrf_firewall_ports[ansible_network_os] %}
         {% if port.vrf == vrf %}
         neighbor {{ port.iface }} interface peer-group ISL
         neighbor {{ port.iface }} local-as {{ evpn_vrf_asn }} no-prepend replace-as         
         {% endif %}
         {% endfor %}
         !
         address-family ipv4 unicast
           neighbor ISL activate
           {% for item in l2_networks %}
           aggregate-address {{ l2_networks[item].ip_subnet }} summary-only attribute-map LOWER_AGGRT_PREF
           {% endfor %}
        address-family l2vpn evpn
           advertise ipv4 unicast
      {% endfor %}
         !
      router bgp {{ ibgp_asn }} vrf {{ internet_vrf }}
         bgp router-id {{ lo_addr }}
         no bgp default ipv4-unicast
         neighbor EDGE peer-group
         neighbor EDGE remote-as external
         neighbor EDGE bfd
         neighbor FW peer-group
         neighbor FW remote-as external
         neighbor FW bfd
         {% for port in internet_vrf_firewall_ports[ansible_network_os] %}
         neighbor {{ port.iface }} interface peer-group FW
         neighbor {{ port.iface }} local-as {{ internet_vrf_asn }} no-prepend replace-as
         {% endfor %}
         {% for port in dcedge_ports[ansible_network_os] %}
         neighbor {{ port.iface }} interface peer-group EDGE
         neighbor {{ port.iface }} local-as {{ internet_vrf_asn }} no-prepend replace-as
         {% endfor %}
         address-family ipv4 unicast
            neighbor FW activate
            neighbor EDGE activate
         !
    marker: '!{mark} edge-firewall-ports'
  notify:
    - reload FRR
