---
- name: Configure NVE (EOS)
  connection: network_cli
  cli_config:
    config: |
      int Vxlan1
         vxlan source-interface {{ vtep_iface }}
         vxlan udp-port 4789
         vxlan learn-restrict any
- name: Configure anycast gateway (EOS)
  connection: network_cli
  cli_config:
    config: |
      ip virtual-router mac-address {{ nxos_fabric_anycast_gw_mac }}
  when: inventory_hostname not in groups['spine']

- name: Configure VNIs (EOS)
  connection: network_cli
  cli_config:
    config: |
      interface Vxlan1
        vxlan vlan {{ item.vlanid }} vni {{ l2_networks[item.vlanid].vnid }}
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined

- name: configure EVPN VRF (EOS)
  connection: network_cli
  cli_config:
    config: |
      vrf instance {{ item.vrf }}
      ip routing vrf {{ item.vrf }}
  with_items: "{{ evpn_l3_info }}"
  when: inventory_hostname not in groups['spine']

- name: Configure L3VNI (EOS)
  connection: network_cli
  cli_config:
    config: |
      interface Vxlan1
        vxlan vrf {{ item.vrf }} vni {{ item.vnid }}
  with_items: "{{ evpn_l3_info }}"

- name: Move SVIs into appropriate VRF
  connection: network_cli
  cli_config:
    config: |
      int {{ l2_networks[item.vlanid].vlanif }}
        no shut
        mtu 9164
        vrf {{ l2_networks[item.vlanid].vrf }}
        ip address virtual {{ l2_networks[item.vlanid].ip_address }}
        mac address virtual-router
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined
