---
- name: Configure NVE/VTEP (NXOS)
  connection: network_cli
  cli_config:
    config: |
      interface nve1
        no shutdown
        advertise virtual-rmac
        host-reachability protocol bgp
        source-interface {{ vtep_iface }}
  when: inventory_hostname not in groups['spine']
  tags: vxlan

- name: Configure anycast gateway (NXOS)
  connection: network_cli
  cli_config:
    config: |
      fabric forwarding anycast-gateway-mac {{ nxos_fabric_anycast_gw_mac }}
  when: inventory_hostname not in groups['spine']

- name: Reconfigure access-list for arp suppression (NXOS)
  connection: network_cli
  cli_config:
    config: |
      hardware access-list tcam region vpc-convergence 0
      hardware access-list tcam region arp-ether 256
- name: Configure VNIs with mcast (NXOS)
  connection: network_cli
  cli_config: 
    config: |
     vlan {{ item.vland }}
       vn-segment {{ l2_networks[item.vlanid].vnid }}
     interface nve1
       !
       member vni {{ l2_networks[item.vlanid].vnid }}
         suppress-arp
         mcast-group {{ item.mcast_grp }}
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined and replication == 'mcast'

- name: Configure VNIs with ingress replication (NXOS)
  connection: network_cli
  cli_config: 
    config: |
     vlan {{ item.vlanid }}
       vn-segment {{ l2_networks[item.vlanid].vnid }}
     interface nve1
       !
       member vni {{ l2_networks[item.vlanid].vnid }}
         suppress-arp
         ingress-replication protocol bgp
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined and replication != 'mcast'

- name: Configure L3VNI (NXOS)
  connection: network_cli
  cli_config:
    config: |
      vlan {{ item.vlan }}
         vn-segment {{ item.vnid }}
      vrf context {{ item.vrf }}
         vni {{ item.vnid }}
      interface {{ item.vlanif }}
        vrf member {{ item.vrf }}
        no shut
        ip forward
        mtu 9216
        
      int nve1
        !
        member vni {{ item.vnid }} associate-vrf
  with_items: "{{ evpn_l3_info }}"
  when: inventory_hostname not in groups['spine']

- name: Move SVIs into appropriate VRF
  connection: network_cli
  cli_config:
    config: |
      int Vlan{{ item.vlanid }}
        vrf member {{ l2_networks[item.vlanid].vrf }}
        no shut
        ip address {{ l2_networks[item.vlanid].ip_address }}
        mtu 9000
        fabric forwarding mode anycast-gateway
  with_items: "{{ l2_ports[ansible_network_os] }}"
  when: l2_ports is defined
