---
- name: Configure ISL ports (NXOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item }}
         no switchport
         no shut
         medium p2p
         ip unnumbered loopback0
         mtu 9200
  with_items: "{{ isl_ports[ansible_network_os] }}"
