---
- hosts: localhost
  tasks:
    - name: Makeup the directory to store configs
      file:
        path: "configs/{{item}}/"
        state: directory
      with_items:
        - nxos
        - eos
        - junos
        - cumulus
      tags: backup
      
- hosts: spine:leaf:exit:dcedge
  gather_facts: false
  roles:
    - role: cfg-hostname
      tags: hostname
    - role: cfg-lo
      tags: loopback
    - role: cfg-lldp
      tags: lldp
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a --force
    - name: reload FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: spine:leaf:exit
  gather_facts: false
  roles:
    - role: cfg-features
      tags: features
    - role: cfg-ospf-isl
      when: underlay == "ospf"
      tags: isl-ports
    - role: cfg-ospf-underlay
      tags: underlay
      when: underlay == "ospf"
    - role: cfg-bgp-isl
      when: underlay == "ebgp"
      tags: isl-ports
    - role: cfg-ebgp-underlay
      when: underlay == "ebgp"
      tags: underlay
    - role: cfg-mlag
      when: mlag is defined and inventory_hostname in groups['leaf']
      tags: mlag
    - role: cfg-server-ports
      when: inventory_hostname in groups['leaf']
      tags: server-ports
    - role: cfg-vxlan
      when: inventory_hostname not in groups['spine']
      tags: vxlan
    - role: cfg-evpn
      tags: evpn
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a --force
    - name: reload FRR
      become: yes
      service:
        name: frr
        state: reloaded

- hosts: exit
  gather_facts: false
  roles:
    - role: cfg-exit-isl
      tags: exit-isl
    - role: cfg-exit-bgp
      tags: exit-bgp
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a --force
    - name: reload FRR
      become: yes
      service:
        name: frr
        state: restarted

- hosts: firewall
  become: yes
  roles:
    - install-frr
    - cfg-fw-interfaces
    - cfg-fw-frr
  
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a --force
    - name: restart FRR
      become: yes
      service:
        name: frr
        state: restarted

- hosts: dcedge
  gather_facts: false
  roles:
    - role: cfg-features
    - role: cfg-num-isl
      tags: dcedge-ifs
    - role: cfg-dcedge-bgp
      tags: dcedge-bgp
    - role: cfg-save
  handlers:
    - name: ifup interfaces
      become: yes
      command: ifup -a --force
    - name: restart FRR
      become: yes
      service:
        name: frr
        state: restarted

- hosts: servers
  become: yes
  roles:
    - role: cfg-dual-attach-servers

- hosts: spine:leaf:exit
  gather_facts: false
  roles:
    - role: cfg-save
      tags: save
    - role: cfg-backup
      tags: backup
    - role: cfg-reboot
      tags: reboot
      when: ansible_network_os == "eos"
  
