---
- name: Configure the server-facing ports (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item.iface }}
         switchport access vlan {{ item.vlanid }}
         mtu 9000
  with_items: " {{ l2_ports[ansible_network_os] }}"

- name: configure SVI (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ l2_networks[item.vlanid].vlanif }}
        no shut
        mtu 9000
        ip address virtual {{ l2_networks[item.vlanid].ip_address }}
  with_items: "{{ l2_ports[ansible_network_os] }}"

