loopback_ip: 10.0.0.12/32
mlag_backup-ip: 10.0.0.12
hw_address: 44:39:39:FF:40:95
bgp_asn: "{{ ibgp_asn }}"
mlag_info:
  clag_sysid: "{{ hw_address }}"
  eos_domainid: mlag_leaf12
  vpc_domainid: 12
  peer_switch: leaf01
  peerlink_ip: 169.254.1.1/31


vtep_ip:
  cumulus:
    - "{{ loopback_ip }}"
    - 10.0.0.112/32
  eos:
    - "{{ loopback_ip }}"
    - 10.0.0.112/32
  nxos:
    - 10.0.0.202/32
    - 10.0.0.112/32


l2_ports:
  cumulus:
    - iface: bond01
      vlanid: 10
    - iface: bond02
      vlanid: 30
  nxos:
    - iface: port-channel3
      vlanid: 10
    - iface: port-channel4
      vlanid: 30
  eos:
    - iface: port-channel3
      vlanid: 10
    - iface: port-channel4
      vlanid: 30
  junos:
    - iface: xe-0/0/2
      vlanid: 10
    - iface: xe-0/0/3
      vlanid: 30

    
