loopback_ip: 10.0.0.11/32
hw_address: 44:39:39:FF:40:95
bgp_asn: "{{ ibgp_asn }}"
mlag_info:
  clag_sysid: "{{ hw_address }}"
  eos_domainid: mlag_leaf12
  vpc_domainid: 12
  peer_switch: leaf02
  peerlink_ip: 169.254.1.0/31
  mlag_backup_ip: 10.0.0.11

vtep_ip:
  cumulus:
    - "{{ loopback_ip }}"
    - 10.0.0.112/32
  eos:
    - "{{ loopback_ip }}"
    - 10.0.0.112/32
  nxos:
    - 10.0.0.201/32
    - 10.0.0.112/32

l2_ports:
  cumulus:
    - iface: bond01
      vlanid: 10
    - iface: bond02
      vlanid: 10
    - iface: bond03
      vlanid: 10
    - iface: bond04
      vlanid: 20
  nxos:
    - iface: port-channel3
      vlanid: 10
    - iface: port-channel4
      vlanid: 10
    - iface: port-channel5
      vlanid: 10
    - iface: port-channel6
      vlanid: 20
  eos:
    - iface: port-channel3
      vlanid: 10
    - iface: port-channel4
      vlanid: 10
    - iface: port-channel5
      vlanid: 10
    - iface: port-channel6
      vlanid: 20
  junos:
    - iface: xe-0/0/2
      vlanid: 10
    - iface: xe-0/0/3
      vlanid: 10
    - iface: xe-0/0/4
      vlanid: 10
    - iface: xe-0/0/5
      vlanid: 20

    
