---
- name: Configure peerlink (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      {% for port in portchannels[ansible_network_os][mlag.peerlink[ansible_network_os]].ports %}
      auto {{ port }}
      iface {{ port }}
        mtu 9200
        post-up ip link set promisc on dev {{ port }}
      #
      {% endfor %}
      auto {{ mlag.peerlink[ansible_network_os] }}
      iface {{ mlag.peerlink[ansible_network_os] }}
         mtu 9200
         bond-slaves {{ portchannels[ansible_network_os][mlag.peerlink[ansible_network_os]].ports | join(' ') }}
      #
    marker: '#{mark} {{mlag.peerlink }}'

- name: Configure CLAG (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{ mlag.peerlink[ansible_network_os]}}.{{mlag.peerlink_vlan }}
      iface {{ mlag.peerlink[ansible_network_os]}}.{{mlag.peerlink_vlan }}
         clagd-peer-ip linklocal
         clagd-sys-mac {{ mlag_info.clag_sysid }}
         clagd-backup-ip {{ loopback_ip }}
         {% if inventory_hostname[-2:]|int%2 == 0 %}
         clagd-priority 1000
         {% else %}
         clagd-priority 32768
         {% endif %}
         clagd-args --initDelay 90
      #
    marker: '#{mark} clag def'
    
- name: Configure member port channels (Cumulus)
  become: yes
  blockinfile:
    path: /etc/network/interfaces
    block: |
      {% for item in mlag.mbr_portchannels[ansible_network_os] %}
      {% for port in item.ports %}
      auto {{ port }}
      iface {{ port }}
         mtu 9000      
         post-up ip link set promisc on dev {{ port }}
      {% endfor %}
      #
      auto {{ item.iface }}
      iface {{ item.iface }}
         bond-slaves {{ item.ports|join(' ') }}
         mtu 9000
         clag-id {{ item.mlag_id }}
         mstpctl-portadminedge yes
         mstpctl-bpduguard yes
         bond-lacp-bypass-allow yes
      #
      {% endfor %}
    marker: '#{mark} mlag-member-ports'
