---
- name: Configure default VRF Firewall ports (Junos)
  connection: network_cli
  cli_config:
    config: |
      set interfaces {{ item.iface }} mtu 9216
      set interfaces {{ item.iface }} flexible-vlan-tagging
      set interfaces {{ item.iface }} encapsulation flexible-ethernet-services
      delete interfaces {{ item.iface }} unit 0
      set interfaces {{ item.iface }} unit {{ item.vlan }} vlan-id {{ item.vlan }}
      set interfaces {{ item.iface }} unit {{ item.vlan }} family inet address {{ item.address }}
  with_items: "{{ default_vrf_firewall_ports[ansible_network_os] }}"

# Assuming EVPN VRfs have been defined by now
- name: Configure EVPN VRFs Firewall ports (Junos)
  connection: network_cli
  cli_config:
    config: |
      set interfaces {{ item.iface }} mtu 9216
      set interfaces {{ item.iface }} flexible-vlan-tagging
      set interfaces {{ item.iface }} encapsulation flexible-ethernet-services
      delete interfaces {{ item.iface }} unit 0      
      set interfaces {{ item.iface }} unit {{ item.vlan }} vlan-id {{ item.vlan }}
      set interfaces {{ item.iface }} unit {{ item.vlan }} family inet address {{ item.address }}
      set routing-instances {{ item.vrf }} interface {{ item.iface }}.{{ item.vlan }}
  with_items: "{{ evpn_vrf_firewall_ports[ansible_network_os] }}"

- name: Configure Internet VRFs Firewall ports (Junos)
  connection: network_cli
  cli_config:
    config: |
      set routing-instances {{ internet_vrf }} instance-type vrf
      set routing-instances {{ internet_vrf }} route-distinguisher {{ lo_addr }}:{{item.vlan}}
      set routing-instances {{ internet_vrf }} vrf-target target:{{ibgp_asn}}:{{item.vlan}}
      set interfaces {{ item.iface }} mtu 9216
      set interfaces {{ item.iface }} flexible-vlan-tagging
      set interfaces {{ item.iface }} encapsulation flexible-ethernet-services
      delete interfaces {{ item.iface }} unit 0      
      set interfaces {{ item.iface }} unit {{ item.vlan }} vlan-id {{ item.vlan }}
      set interfaces {{ item.iface }} unit {{ item.vlan }} family inet address {{ item.address }}
      set routing-instances {{ internet_vrf }} interface {{ item.iface }}.{{ item.vlan }}
  with_items: "{{ internet_vrf_firewall_ports[ansible_network_os] }}"

# Assuming Internet VRF has been defined already above
- name: Configure DCEdge port (Junos)
  connection: network_cli
  cli_config:
    config: |
      delete interfaces {{ item.iface }} unit 0 family inet dhcp
      set interfaces {{ item.iface }} unit 0 family inet address {{ item.address }}
      set routing-instances {{ internet_vrf }} interface {{ item.iface }}.0
  with_items: "{{ dcedge_ports[ansible_network_os] }}"
